---
version: '2'
services:
  web:
    build: xmpp.org
    image: xmppxsf/xmpp.org
    ports:
      - "127.0.0.1:7001:80"
    restart: unless-stopped
  xeps:
    #image: xmppxsf/xeps
    image: registry.gitlab.com/xsf/xeps/packed:main-latest
    ports:
      - "127.0.0.1:7002:80"
    restart: unless-stopped
  attic:
    #image: xmppxsf/xep-attic
    image: registry.gitlab.com/xsf/xep-attic/packed:main-latest
    ports:
      - "127.0.0.1:7004:80"
    restart: unless-stopped
  wiki:
    image: xmppxsf/mediawiki
    ports:
      - "127.0.0.1:7003:80"
    links:
      - wiki_db
    env_file:
      - ./wiki_db.env
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
      - /docker/wiki.xmpp.org/data/mediawiki/data/images:/var/www/html/images
      #- /docker/wiki.xmpp.org/data/mediawiki/data/extensions:/var/www/html/extensions
    restart: unless-stopped
  wiki_db:
    image: postgres:9.6
    #image: postgres:11
    env_file:
      - ./wiki_db.env
    volumes:
      - /docker/wiki.xmpp.org/data/postgres/var_lib_postgrestql_data:/var/lib/postgresql/data
    restart: unless-stopped
  registrar:
    image: xmppxsf/registrar
    build: registrar
    ports:
    - "127.0.0.1:7005:80"
    restart: unless-stopped
